POST http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAxMTk4NzEsInN1YiI6ImUxYzUyMGZhLTM4MGMtNDE5Mi05ZTY4LWFkZTU0NzBkNDdhYyJ9.1nB3ZBRlm2E5oKtrjT3d8ypRwHESUCjJkN2YxVuvTNo
Content-Type: application/json

{
  "name": "Sample Product 10",
  "price": 19.90
}

###
GET http://localhost:8000/products/75f33afa-c10e-4b39-a20f-371fcfe5088a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAxMTk4NzEsInN1YiI6ImUxYzUyMGZhLTM4MGMtNDE5Mi05ZTY4LWFkZTU0NzBkNDdhYyJ9.1nB3ZBRlm2E5oKtrjT3d8ypRwHESUCjJkN2YxVuvTNo
###
GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAxMTk4NzEsInN1YiI6ImUxYzUyMGZhLTM4MGMtNDE5Mi05ZTY4LWFkZTU0NzBkNDdhYyJ9.1nB3ZBRlm2E5oKtrjT3d8ypRwHESUCjJkN2YxVuvTNo
Content-Type: application/json
###
PUT http://localhost:8000/products/ccea2d53-f3ad-4f6d-a00b-2b4f00e2e246 HTTP/1.1
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 24.99
}
###
DELETE http://localhost:8000/products/ccea2d53-f3ad-4f6d-a00b-2b4f00e2e246 HTTP/1.1
Content-Type: application/json
###